language: csharp
mono: none
dotnet: 6.0

install:
  - dotnet restore

script:
  - dotnet tool install --global coveralls.net --version 2.0.0
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - dotnet test --collect:"XPlat Code Coverage"
  
